add Uploader component
WANNABY/wanna-ant-uploader pull request #1
Opened 2020-11-17 22:47 UTC by mouseluka

2020-11-18 16:26 UTC, igor-lemon requested changes

2020-11-18 16:26 UTC, igor-lemon commented on README.md
> +<p align="center">
Car Readme. Add a simple example how to use the component

2020-11-18 16:26 UTC, igor-lemon commented on components/upload/Upload.tsx
> +  const onChange = (info: UploadChangeParam) => {
if you set a custom method the name should start `handle` prefix

2020-11-18 16:26 UTC, igor-lemon commented on components/upload/Upload.tsx
> +  const onStart = (file: RcFile) => {
if you set a custom method the name should start `handle` prefix

2020-11-18 16:26 UTC, igor-lemon commented on components/upload/Upload.tsx
> +  const onSuccess = (response: any, file: UploadFile, xhr: any) => {
if you set a custom method the name should start `handle` prefix

2020-11-18 16:26 UTC, igor-lemon commented on components/upload/Upload.tsx
> +  const onProgress = (e: { percent: number }, file: UploadFile) => {
if you set a custom method the name should start `handle` prefix

2020-11-18 16:26 UTC, igor-lemon commented on components/upload/Upload.tsx
> +  const onFileDrop = (e: React.DragEvent<HTMLDivElement>) => {
if you set a custom method the name should start `handle` prefix

2020-11-18 18:14 UTC, mouseluka commented on components/upload/Upload.tsx
> +  const onChange = (info: UploadChangeParam) => {
discussed

2020-11-18 18:14 UTC, mouseluka commented on components/upload/Upload.tsx
> +  const onStart = (file: RcFile) => {
discussed

2020-11-18 18:14 UTC, mouseluka commented on components/upload/Upload.tsx
> +  const onSuccess = (response: any, file: UploadFile, xhr: any) => {
discussed

2020-11-18 18:14 UTC, mouseluka commented on components/upload/Upload.tsx
> +  const onProgress = (e: { percent: number }, file: UploadFile) => {
discussed

2020-11-18 18:14 UTC, mouseluka commented on components/upload/Upload.tsx
> +  const onFileDrop = (e: React.DragEvent<HTMLDivElement>) => {
discussed

2020-11-19 11:28 UTC, igor-lemon approved these changes

2020-11-19 11:28 UTC, merged